kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: my-python-app-build
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'my-python-app:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: python-app/Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/gebah/Breakout.git'
  runPolicy: Serial
